name: ci
on: [push]
jobs:
  build:
    name: Build and Collects artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Checkout Submodules
        shell: bash
        run: |
          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: sh Extras/build_all.sh
      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: bin/Release/net5.0/win-x64/publish/
      - uses: actions/upload-artifact@v4
        with:
          name: osx
          path: bin/Release/net5.0/osx-x64/publish/
      - uses: actions/upload-artifact@v4
        with:
          name: linux-ubuntu-18.04
          path: bin/Release/net5.0/ubuntu.18.04-x64/publish/
